docker rmi $(docker images -q)
docker build -t image-telegraf ./telegraf
docker build -t image-nginx ./nginx
docker build -t image-phpmyadmin ./phpmyadmin
docker build -t image-mysql ./mysql
docker build -t image-wordpress ./wordpress
docker build -t image-influxdb ./influxdb
docker build -t image-grafana ./grafana
docker build -t image-ftps ./ftps