apiVersion: v1
kind: Service
metadata:
  name: service-influxdb
  labels:
    app: label-influxdb
spec:
  selector:
    app: label-influxdb
  ports:
    - port: 8086
      targetPort: 8086
  type: LoadBalancer
  externalIPs:
  - 192.168.99.111
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inflx-pv-claim
  labels:
    app: label-influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflx-deploy
  labels:
    app: label-influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-influxdb
  template:
    metadata:
      labels:
        app: label-influxdb
    spec:
      containers:
      - image: image-influxdb
        name: cont-influxdb
        ports:
        - containerPort: 8086
          name: influxdb
        volumeMounts:
          - name: inflx-data
            mountPath: "/var/lib/influxdb"
          - name: inflx-config
            mountPath: /etc/influxdb/influxdb.conf
            subPath: influxdb.conf
            readOnly: true
        imagePullPolicy: Never
      volumes:
      - name: inflx-data
        persistentVolumeClaim:
          claimName: inflx-pv-claim
      - name: inflx-config
        configMap:
          name: inflx-config