apiVersion: v1
kind: Service
metadata:
  name: service-influxdb
spec:
  ports:
  - port: 8086
    targetPort: 8086
    name: influxdb
    protocol: TCP
  selector:
    app: label-influxdb
  type: LoadBalancer
  externalIPs:
  - 192.168.99.111

---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: influxdb-volume
#   labels:
#     app: label-influxdb
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: influxdb-deploy
#   labels:
#     app: label-influxdb
# spec:
#   selector:
#     matchLabels:
#       app: label-influxdb
#   template:
#     metadata:
#       labels:
#         app: label-influxdb
#     spec:
#       containers:
#         - image: image-influxdb
#           name: cont-influxdb
#           ports:
#             - containerPort: 8086
#               name: influxdb
#           imagePullPolicy: Never

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deploy
spec:
  selector:
    matchLabels:
      app: label-influxdb
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: label-influxdb
    spec:
      containers:
        - image: image-influxdb
          name: cont-influxdb
          ports:
            - containerPort: 8086
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: influxdb-data
            - mountPath: /etc/influxdb/influxdb.conf
              name: influxdb-config
              subPath: influxdb.conf
              readOnly: true
          imagePullPolicy: Never
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-data
        - name: influxdb-config
          configMap:
            name: influxdb-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
data:
  influxdb.conf: |
    bind-adress="127.0.0.1:8088"
    [meta]
      dir="/var/lib/influxdb/meta"
    [data]
      dir="/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"
      trace-logging-enable=true
    [http]
      bind-addres=":8086"
      log-enabled=true
    [[graphite]]
      database="telegraf"