apiVersion: v1
kind: Service
metadata:
  name: service-influxdb
spec:
  ports:
  - port: 8086
    targetPort: 8086
    name: influxdb
    protocol: TCP
  selector:
    app: label-influxdb
  type: LoadBalancer
  externalIPs:
  - 192.168.99.109

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-volume
  labels:
    app: label-influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deploy
  labels:
    app: label-influxdb
spec:
  selector:
    matchLabels:
      app: label-influxdb
  template:
    metadata:
      labels:
        app: label-influxdb
    spec:
      containers:
        - image: image-influxdb
          name: cont-influxdb
          ports:
            - containerPort: 8086
              name: influxdb
          imagePullPolicy: Never