apiVersion: v1
kind: Service
metadata:
  name: service-mysql
  # annotations:
  #   metallb.universe.tf/address-pool: production-public-ips
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
    protocol: TCP
  selector:
    app: label-mysql
  type: LoadBalancer
  externalIPs:
  - 192.168.99.109

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume
  labels:
    app: label-mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: label-mysql
spec:
  selector:
    matchLabels:
      app: label-mysql
  template:
    metadata:
      labels:
        app: label-mysql
    spec:
      containers:
        - image: image-mysql
          name: cont-mysql
          ports:
            - containerPort: 3306
              name: mysql
          imagePullPolicy: Never