apiVersion: v1
kind: Service
metadata:
  name: service-phpmyadmin
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: phpmyadmin
    protocol: TCP
  selector:
    app: label-phpmyadmin
  type: LoadBalancer
  externalIPs:
  - 192.168.99.107

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deploy
  labels:
    app: label-phpmyadmin
spec:
  selector:
    matchLabels:
      app: label-phpmyadmin
  template:
    metadata:
      labels:
        app: label-phpmyadmin
    spec:
      containers:
        - image: image-phpmyadmin