apiVersion: v1
kind: Service
metadata:
  name: service-ftps
spec:
  selector:
    app: label-ftps
  ports:
    - protocol: TCP
      name: ftps-21
      port: 21
      targetPort: 21
    - protocol: TCP
      name: ftps-21009
      port: 21009
      targetPort: 21009
    - name: ftps-20
      protocol: TCP
      port: 20
      targetPort: 20
  type: LoadBalancer
  externalIPs:
  - 192.168.99.111
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
  labels:
    app: label-ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-ftps
  template:
    metadata:
      labels:
        app: label-ftps
    spec:
      containers:
      - image: image-ftps
        name: cont-ftps
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21009
        volumeMounts:
        - name: ftps
          mountPath: /ftp
        imagePullPolicy: Never
      volumes:
      - name: ftps
        persistentVolumeClaim:
          claimName: ftps-pv-claim