apiVersion: v1
kind: Service
metadata:
  name: service-mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
    protocol: TCP
  selector:
    app: label-mysql

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume
  labels:
    app: label-mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: label-mysql
spec:
  selector:
    matchLabels:
      app: label-mysql
  template:
    metadata:
      labels:
        app: label-mysql
    spec:
      containers:
        - image: image-mysql
          name: cont-mysql
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
          imagePullPolicy: Never
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql-volume